#!/bin/bash -e

#
# Install NVM and node
#
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.23.2/install.sh | bash
export NVM_DIR="/home/vagrant/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm install stable
nvm alias default stable
