#!/bin/bash -e

#
# Global deps
#
sudo apt-get update
sudo apt-get install -y make g++ ruby
sudo gem install compass

#
# Install NVM and node
#
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.23.2/install.sh | bash
export NVM_DIR="/home/vagrant/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm install stable
nvm alias default stable

#
# Install project deps
#

 npm install -g node-gyp
 cd /vagrant
 npm install
